apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <ca>
    server: https://10.129.0.21:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: cd
  name: cd@kubernetes
current-context: cd@kubernetes
kind: Config
preferences: {}
users:
- name: cd
  user:
    token: <token>
