---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: homework
  name: admin
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd-admin
  namespace: homework
subjects:
- kind: ServiceAccount
  name: cd
  apiGroup: v1
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
