apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: my-pvc
        - name: config
          configMap:
            name: my-cm
      initContainers:
        - name: generate-index
          image: busybox
          command: ["sh", "-c"]
          args: ["echo '<html><p>Hellow world!</p></html>' > /init/index.html"]
          volumeMounts:
            - name: data-volume
              mountPath: /init
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.version }}
          ports:
            - containerPort: {{ .Values.container.port }}
          command: ["python"]
          args: ["-m", "http.server", "8000", "--directory", "/homework"]
          volumeMounts:
            - name: data-volume
              mountPath: /homework
            - name: config
              mountPath: /homework/conf
          {{- if eq .Values.probesEnabled "true" }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.container.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.container.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          {{- end }}